/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "Coins"

pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}
