main: '${project.groupId}.${project.name}'
name: '${project.name}'
version: '${project.version}'
website: '${project.url}'
description: '${project.description}'
api-version: '${versions.minecraft}'
authors: [JustEli]
softdepend: [Vault, MythicMobs, OrangDomain]
libraries:
  - 'net.kyori:adventure-platform-bukkit:${versions.adventure-platform-bukkit}'
  - 'net.kyori:adventure-text-minimessage:${versions.adventure}'
  - 'net.kyori:adventure-text-serializer-legacy:${versions.adventure}'
  - 'net.kyori:adventure-text-serializer-plain:${versions.adventure}'
commands:
  coins:
    description: 'Command for showing all available commands from Coins. Also used for various admin tools.'
    permission: 'coins.command'
    usage: '/<command> [reload|settings|drop|remove|language|version|toggle]'
    aliases:
      - coin
  withdraw:
    description: 'Withdraw money from your balance into physical coins.'
    permission: 'coins.withdraw'
    usage: '/<command> <worth> [amount]'
permissions:
  'coins.command':
    default: true
  'coins.command.reload':
    description: 'Access to /coins reload.'
    default: op
  'coins.command.settings':
    description: 'Access to /coins settings.'
    default: op
  'coins.command.language':
    description: 'Access to /coins language.'
    default: op
  'coins.command.version':
    description: 'Access to /coins version.'
    default: op
  'coins.command.toggle':
    description: 'Access to /coins toggle.'
    default: op
  'coins.command.drop':
    description: 'Access to /coins drop.'
    default: op
  'coins.command.remove':
    description: 'Access to /coins remove.'
    default: op
  'coins.withdraw':
    description: 'Access to /withdraw, and ability to withdraw and deposit coins.'
    default: op
  'coins.bypass.lose_on_death':
    description: 'Bypass the mechanic that lets your lose coins on death.'
    default: false
  'coins.bypass.percentage_hit':
    description: 'Bypass the minimum percentage to hit a mob before it drops coins.'
    default: false
  'coins.bypass.location_limit':
    description: 'Bypass the limit for killing mobs in a single location.'
    default: false
  'coins.drop.spawner_mobs':
    description: 'Always get coins for killing mobs from spawners.'
    default: false
  'coins.drop.split_mobs':
    description: 'Always get coins for killing split mobs, like slimes.'
    default: false
  'coins.drop.hostile_mobs':
    description: 'Always get coins for killing hostile mobs.'
    default: false
  'coins.drop.passive_mobs':
    description: 'Always get coins for killing passive mobs.'
    default: false
  'coins.drop.players':
    description: 'Always get coins for killing other players.'
    default: false
  'coins.disable':
    description: 'Permission to give to players to disable coin pickup for them.'
    default: false
  'coins.multiplier.n':
    description: 'Permission to give to players to get multiplied coin drops. Replace /n/ with a number.'
    default: false
